### ISSUE TITLE
cannot print error message

### ISSUE THREAD

**Issue by denigada** [binance-exchange/node-binance-api#102]
binance.buy(pair, order.amount, order.bidAsk, { type: 'LIMIT' }, (error, response) => { if (error) { console.log('ERROR PLACING ORDER: ' + error.msg);

It is printing undefined. I also tried error.body.msg but it doesn't work. How does everyone get the error messages?

**Comment by jaggedsoft** [comment]
```js
			binance.marketBuy(symbol, amount, (error, response) => {
				if ( error ) return console.error("marketBuy",error,response);
				console.log("..Market Buy response", response);
				console.log("..order id: " + response.orderId);
			});
```

**Comment by denigada** [comment]
How can I get the actual error message as a string?

**Comment by jaggedsoft** [comment]
maybe make a new function
then `if ( error ) return handleError(error, "buy()");`

```js
function handleError(error, note = "handleError") {
let code = typeof error.code === "undefined" ? 0 : error.code;
let msg = typeof error.msg === "undefined" ? error : error.msg;
console.error(note+": error #"+code, msg);
}
```

**Comment by denigada** [comment]
This code prints the same output as if I just do console.log(error), a pretty long JSON data

**Comment by denigada** [comment]
All I had to do is console.log(error.body.msg)
