### ISSUE TITLE
Get all open orders on an account

### ISSUE THREAD

**Issue by evancaldwell** [binance-exchange/node-binance-api#104]
I don't see any way to get all open orders for an account - only getting all open orders on an account for a specific symbol. Is there a way (or template) for getting all open orders for all symbols?

**Comment by keith1024** [comment]
Yip. Just pass `false` to the `openOrders()` call.

```javascript
binance.openOrders(false, (error, openOrders) => {
  console.log("openOrders()", openOrders);
});
```

**Comment by evancaldwell** [comment]
Ok great. Thank you.

**Comment by keith1024** [comment]
You're welcome. You missed it in the readme. ;)
