### ISSUE TITLE
No response object on STOP_LOSS_LIMIT order

### ISSUE THREAD

**Issue by evancaldwell** [binance-exchange/node-binance-api#105]
I'm trying to place a STOP_LOSS_LIMIT order with a callback but the response object is empty. Here's the code I'm using:
```
let entryData = {
  currencyPair: 'BTCUSDT',
  purchasePrice: 9480,
  lastPrice: 9480,
  stopPrice: 9580,
  qty: 0.01
};

binance.sell(entryData.currencyPair, entryData.qty, entryData.lastPrice, {stopPrice: entryData.stopPrice, type: 'STOP_LOSS_LIMIT'}, (error, response) => {
  if (error) {
    console.log('stop_loss error: ', error.body);
  } else {
    console.log('after initialStop: ', response);
  }
});
```
and the console output is:
`after initialStop:  {}`

If there is an error it seems to output the error just fine.

**Comment by keith1024** [comment]
Just double checking, you don't by any change have the `options.test` flag set to `true`? This will always get an empty `{}` object returned from Binance. Test mode is to make sure you have no errors in your order request, and gives you an idea of how long Binance will take to process your request, so you can squeeze your `recvWindow` as low as possible.

**Comment by evancaldwell** [comment]
Ah, I see. I do have `test` set to `true`.  I'll try it without and let you know then.

**Comment by seleckis** [comment]
I have the same issue. Wouldn't it be better to return some dummy response with the same structure? Don't think it is a good idea to spend real coins for testing :)
