### ISSUE TITLE
Keep connection even on error

### ISSUE THREAD

**Issue by amelenetwork** [binance-exchange/node-binance-api#108]
Hello there !

I need to help about keep connection if even get error . I have not so much experience Node.js , Im testing codes , working 1 hour for example below codes;

binance.prevDay(false, (error, prevDay) => {
  let markets = [];
  for ( let obj of prevDay ) {
    let symbol = obj.symbol;
    console.log(symbol+" volume:"+obj.volume+" change: "+obj.priceChangePercent+"%");
    markets.push(symbol);
  }

  
  binance.websockets.candlesticks(markets, '15m', (candlestickData) => {
    let tick = binance.last(candlestickData);
    const symbol = candlestickData.s;
    const close = candlestickData[tick].c;
    console.log(symbol+": "+close);
  });

  
});

then getting error 504 somethings.... 

I understand - error we can get no problem but, I want to manage this error . Script is stoping to work after error, cutting down . I want to this script  keep work even get error, script should try to re-connect and keep work always . 

For example , if **try - catch block** we can use - i think script will continue to work . 

For example like this...

try {
  client.getOrderBook("UNKNOWN", 10);
} catch (BinanceApiException e) {
  System.out.println(e.getError().getCode()); // -1121
  System.out.println(e.getError().getMsg());  // Invalid symbol
}

Anybody help me ? How can i fix this ? how can I catch error and keep running script ?

Thank you !

**Comment by jaggedsoft** [comment]
504 error is a Gateway Timeout
Your code is doing this from getting the order book? I believe the problem would be with the design of your getOrderBook function. I would need to see it in order to provide a solution

**Comment by amelenetwork** [comment]
I get this error just now :( 

I don't know how i will fix these errors ... I need to keep UP this script - keep work always ...

[ 'WebSocket Unexpected response: 1563083098' ]
C:\www\laravel\node_modules\node-binance-api\node-binance-api.js:222
            if ( reconnect && options.reconnect ) {
            ^

ReferenceError: reconnect is not defined
    at WebSocket._handleSocketUnexpectedResponse (C:\www\laravel\node_modules\node-binance-api\node-binance-api.js:222:13)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at ClientRequest._req.on (C:\www\laravel\node_modules\ws\lib\WebSocket.js:651:15)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)

**Comment by jaggedsoft** [comment]
The code has improved considerably since the version you have
Navigate to your project directory and `npm update` and see if it works

**Comment by amelenetwork** [comment]
I updated ...

Now i get error again but re-connect self . 

Pump K-Line Fonksion calisti....
[ 'WebSocket error: 1563083098 unexpected server response (502)' ]
[ 'WebSocket closed: 1563083098 (1006)' ]
[ 'WebSocket reconnecting: 1563083098...' ]

I hope it's will work . 

Thank you !!!

**Comment by jaggedsoft** [comment]
Sounds great let me know if you have any problems
Always happy to help
