### ISSUE TITLE
package.json missing?

### ISSUE THREAD

**Issue by carlosbaraza** [binance-exchange/node-binance-api#11]
Why there is no package.json in this repository?

**Comment by jaggedsoft** [comment]
Is it necessary? NPM should download it remotely from here:
https://www.npmjs.com/package/node-binance-api

Here is the contents:
```
{
  "name": "node-binance-api",
  "version": "0.2.11",
  "description": "Binance API for node https://github.com/jaggedsoft/node-binance-api",
  "main": "node-binance-api.js",
  "dependencies": {
    "request": "^2.83.0",
    "ws": "^3.2.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/jaggedsoft/node-binance-api.git"
  },
  "keywords": [
    "binance",
    "api"
  ],
  "author": "Jon Eyrick <social@nextlocal.net> (https://nextlocal.net)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/jaggedsoft/node-binance-api/issues"
  },
  "homepage": "https://github.com/jaggedsoft/node-binance-api#readme"
}
```

**Comment by carlosbaraza** [comment]
The thing is that using an API wrapper where I will put API keys is already quite a potential security flaw. Having a `package.json` would allow people to easily fork the repository and use their version of the code, which is guaranteed to be secure, as they could review it. It is slightly more difficult to verify that the version of this module published to NPM is actually secure/not malicious.

Also, I just don't understand why not to follow the convention everyone follows regarding NPM modules. If this is an NPM module, not sure why the `package.json` is not added to the repo.
