### ISSUE TITLE
Market Depth Chart - Total Orders

### ISSUE THREAD

**Issue by amelenetwork** [binance-exchange/node-binance-api#111]
Hello there...

This is not looks like issue but I don't know how can I do that . I hope anybody can answer to me. 

On binance.com web site there is showing Depth Chart, there is total orders explaining on chart . You can check screen shot . 

https://prnt.sc/inh55f

I need like this chart , Im getting data with;

binance.websockets.depthCache('BTCUSDT', (symbol, depth) => {
......
......
});

But there is answer just price and quantity orders . 

I'i doing SUM all BID or ASK orders then , step by step MINUS last one BACK to FORWARD . 

It's looks like for me very "primitive" . Not looks like instant and taking time and cost . 

Is there any good and modern option to get data MARKET DEPTH CHART ? 

How can i do that ? 

Thank you so much....

**Comment by jaggedsoft** [comment]
For this type of chart bids/asks are cumulative. So you add the btc value

![image](https://user-images.githubusercontent.com/4283360/37023492-fd1c4a5c-20da-11e8-8aba-b3e657afd645.png)
[view code on jsfiddle](https://jsfiddle.net/jaggedsoftware/kjkLgsbx/)

I have a websocket function to return the values in cumulative format
I get the data like this:
```js
const file = require('fs');
binance.websockets.depthCache(['BTCUSDT','BNBBTC'], (symbol, depth) => {
	const limit = 1000;
	let bids = binance.sortBids(depth.bids, limit, 'cumulative');
	let asks = binance.sortAsks(depth.asks, limit, 'cumulative');
	console.log(symbol+" depth cache update");
	console.log("best bid: "+binance.first(bids));
	console.log("best ask: "+binance.first(asks));
	let output = {bids:bids, asks:asks};
	// save information to json file
	file.writeFile("json/depth/"+symbol+".json", JSON.stringify(output, null, 4), (err)=>{});
});
```

**Comment by amelenetwork** [comment]
You are amazing my friend .

Thank you so much !

**Comment by jaggedsoft** [comment]
Good luck!
I just realized highcharts data needs to be in array format
So you will need to do this instead:

```js
let output = {bids:binance.array(bids), asks:binance.array(asks)};
```

**Comment by amelenetwork** [comment]
Thank you my friend . 

i appreciate your help !
