### ISSUE TITLE
Exchange data chart type

### ISSUE THREAD

**Issue by amelenetwork** [binance-exchange/node-binance-api#114]
Hello there !

I need help again.. I hope you can answer... 

https://prnt.sc/ioga36

Which chart is this ? Highchart or what ? Where can i found this chart sources ? I want to build same as like this look for mobile resolutions . 

What is your ideas fellows ? 

Thank you for sharing.

**Comment by jaggedsoft** [comment]
This is kline: https://github.com/chxj1992/kline
I have code to make it work with this library. My version uses PHP to get around CORS security issues

**Comment by jaggedsoft** [comment]
![image](https://user-images.githubusercontent.com/4283360/37172433-9c45d7ba-22c5-11e8-9dd3-6f89508fbd61.png)

**Comment by jaggedsoft** [comment]
![image](https://user-images.githubusercontent.com/4283360/37172540-ee520a92-22c5-11e8-86d5-216dfffd6323.png)

**Comment by amelenetwork** [comment]
# Thank you so much....

**Comment by jaggedsoft** [comment]
no problem, there are two undocumented built-in functions in this library that are very useful for charting.
`.highstock(chart)` will return the data in array format `[open, high, low, close, volume]`
`.ohlc(chart)` will return the data in object format `.open .high .low .close .volume`

```js
        // convert chart data to highstock array [timestamp,open,high,low,close]
        highstock: function(chart, include_volume = false) {
            let array = [];
            for ( let timestamp in chart ) {
                let obj = chart[timestamp];
                let line = [
                    Number(timestamp),
                    parseFloat(obj.open),
                    parseFloat(obj.high),
                    parseFloat(obj.low),
                    parseFloat(obj.close)
                ];
                if ( include_volume ) line.push(parseFloat(obj.volume));
                array.push(line);
            }
            return array;
        },
        ohlc: function(chart) {
            let open = [], high = [], low = [], close = [], volume = [];
            for ( let timestamp in chart ) { //ohlc[symbol][interval]
                let obj = chart[timestamp];
                open.push(parseFloat(obj.open));
                high.push(parseFloat(obj.high));
                low.push(parseFloat(obj.low));
                close.push(parseFloat(obj.close));
                volume.push(parseFloat(obj.volume));
            }
            return {open:open, high:high, low:low, close:close, volume:volume};
        },
```
