### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by sunabozu** [binance-exchange/node-binance-api#12]
Hi.

After making any request I get the following error in my browser:

`Failed to load https://api.binance.com/api/v1/ticker/allPrices: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Is there any additional steps I have to take in order to make it work?

**Comment by jaggedsoft** [comment]
No exchanges allow API requests to be run from the browser or plugins. This can only be run from node js

**Comment by sunabozu** [comment]
Oh, I didn't know that, sorry.
