### ISSUE TITLE
About Binance sparkline chart type

### ISSUE THREAD

**Issue by mkhuman34** [binance-exchange/node-binance-api#121]
Hello there !

I want to ask about chart type if anybody know that ...

There is "sparkline" chart but which project ? Where can I found this chart type and use with "node-binance-api"

There is SS . 

https://prnt.sc/ivlf1c

Thank you for your support !!!

**Comment by jaggedsoft** [comment]
That is just taking the 'close' values for each candlestick
The easiest way to do this is with Google Image Charts, Google Charts, or Highstock. Personally I made my own function to generate SVG's (I will share it in the future)

Here is a simple function using Google Image Charts
```js
// Intervals: 1m,3m,5m,15m,30m,1h,2h,4h,6h,8h,12h,1d,3d,1w,1M
binance.candlesticks("BTCUSDT", "15m", (error, ticks, symbol) => {
	let values = [];
  for ( let tick of ticks ) {
  		let [time, open, high, low, close, volume, closeTime, assetVolume, trades, buyBaseVolume, buyAssetVolume, ignored] = tick;
  		values.push(close);
	}
	console.log(image_chart(values));
}, {limit: 50});
function image_chart(close, color = "1976D2", size = "300x40", lineWidth = 3) {
	let values = close.slice(-50);
	let min = Math.min(...values);
	let max = Math.max(...values);
	return "https://chart.apis.google.com/chart?cht=ls&chf=bg,s,00000000&chco="+color+"&chd=t:"+values.join(',')+"&chls="+lineWidth+"&chs="+size+"&chds="+min+","+max;
}
```
Now you can create an image chart for BTCUSDT, or any other symbol you'd like.
![image](https://user-images.githubusercontent.com/4283360/37860466-ed3a19dc-2ee2-11e8-89fb-f586d6dce24c.png)

You can also use websocket functions that always update json files so you have realtime data
I posted some examples of this here: https://github.com/binance-exchange/node-binance-api/issues/116

**Comment by mkhuman34** [comment]
Thank you my friend !

This is old " amelenetwork"

My account is changed ... I think you understand about my question too :) 

Thank you again !
