### ISSUE TITLE
i npm node-binance-api,it show wrong

### ISSUE THREAD

**Issue by aw12sds** [binance-exchange/node-binance-api#123]
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "node-binance-api" under a package
npm ERR! also called "node-binance-api". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

**Comment by jaggedsoft** [comment]
I think this is why you need to do this: `npm i node-binance-api --save`
I'm not sure why, though. Probably an issue with our package.json

**Comment by kianhung** [comment]
Still the same with your command above, any help would be appreciate =)

npm i node-binance-api --save
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "node-binance-api" under a package
npm ERR! also called "node-binance-api". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

**Comment by jaggedsoft** [comment]
I have no idea what is causing this, sorry. You should probably install in a new folder
