### ISSUE TITLE
Version 0.4.26 - Cannot read property '**filter**' of undefined

### ISSUE THREAD

**Issue by mkhuman34** [binance-exchange/node-binance-api#125]
C:\www\laravel\node_modules\node-binance-api\**node-binance-api.js:915**
                        context.messageQueue = context.messageQueue.filter(depth => depth.u > context.snapshotUpdateId);
                                                                    ^

TypeError: Cannot read property '**filter**' of undefined
    at C:\www\laravel\node_modules\node-binance-api\node-binance-api.js:915:69
    at Request._callback (C:\www\laravel\node_modules\node-binance-api\node-binance-api.js:66:20)
    at Request.self.callback (C:\www\laravel\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\www\laravel\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\www\laravel\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)

-------------------

Same codes working very well 0.4.25 version ....

Good luck !

**Comment by mkhuman34** [comment]
now my old versions giving errors too :( 

I updated then all my system destroyed :( - i get back old version now not working too.. I don't understand ...

All was good .....

$ node markets.js
Server started....
Waiting connectin from //laravel.bitex
Listening port: 2121
C:\www\laravel\markets.js:55
  for ( let obj of prevDay ) {
                   ^

TypeError: prevDay is not iterable
    at binance.prevDay (C:\www\laravel\markets.js:55:20)
    at C:\www\laravel\node_modules\node-binance-api\node-binance-api.js:696:49

**Comment by jaggedsoft** [comment]
I can confirm everything is working properly for me. Try adding some error messages / running this test code:
```js
binance.prevDay(false, (error, prevDay) => {
	if ( error ) return console.error("prevDay error: ", error);
	for ( let obj of prevDay ) {
		let symbol = obj.symbol;
		console.log(symbol+" volume:"+obj.volume+" change: "+obj.priceChangePercent+"%");
	}
});
```

Is your system time set correctly? If not you will need to try the `useServerTime` option

**Comment by mkhuman34** [comment]
body: '{"code":-1003,"msg":"Way too many requests; IP banned until 1522523427617. Please use the websocket for live updates to avoid bans."}' }

**Comment by mkhuman34** [comment]
There was no any problem - system was working really so so good - last 4 days worked no any error really was so good ...

I updated then BLOCK I think

**Comment by mkhuman34** [comment]
Starting system...

My system getting all data from all coins on binance.. it was really worked so so super until to update . now old files to not working , it's interesting  . Binance did any update on their side ?

Getting data several times ... Then blocking to me :(

$ node markets.js
Server started....
Waiting connectin from //laravel.bitex
Listening port: 2121
Here...
Here...
Here...
Here...
Here...
Here...
Here...
Here...
Here...
Here...
C:\www\laravel\node_modules\node-binance-api\node-binance-api.js:915
                        context.messageQueue = context.messageQueue.filter(depth => depth.u > context.snapshotUpdateId);
                                                                    ^

TypeError: Cannot read property 'filter' of undefined
    at C:\www\laravel\node_modules\node-binance-api\node-binance-api.js:915:69
    at Request._callback (C:\www\laravel\node_modules\node-binance-api\node-binance-api.js:64:24)
    at Request.self.callback (C:\www\laravel\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\www\laravel\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\www\laravel\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by mkhuman34** [comment]
Hello again...

I turn to version "# **v0.4.24**" extract from ZIP file, then all is working normal like as old times....

I love this warn so much.... These are not important - important is IP not blocking ans system working ....


Here...
Here...
[ 'depthHandler :STORJBTC: Unexpected first depth event. Skipping. !! IF this pe
rsists, the "STORJBTC" cache is OUT OF SYNC !! ' ]
[ 'depthHandler :ZECBTC: Unexpected first depth event. Skipping. !! IF this pers
ists, the "ZECBTC" cache is OUT OF SYNC !! ' ]
[ 'depthHandler :AMBBTC: Unexpected first depth event. Skipping. !! IF this pers
ists, the "AMBBTC" cache is OUT OF SYNC !! ' ]
[ 'depthHandler :MANABTC: Unexpected first depth event. Skipping. !! IF this per

[ 'depthHandler :STORMBTC: Unexpected first depth event. Skipping. !! IF this pe
rsists, the "STORMBTC" cache is OUT OF SYNC !! ' ]
Here...
Here...

**Comment by mkhuman34** [comment]
I turn to version "# **v0.4.24**" extract from ZIP file, then all is working normal like as old times....

Looks like working for now ... 

I hope keep will work. 

Please check last version about requesting sizes .... I think there is some ISSUE on last version

**Comment by jaggedsoft** [comment]
BANNED is from making too many requests. Slow down your program so you don't make so many requests when you first start it if this keeps up. Otherwise, wait an hour or two and try again.

**Comment by mkhuman34** [comment]
mate but you are forgetting this .. same codes working with version  v0.4.24 very well ... 

now Im working with old version  v0.4.24 ( there is miniTicker too ) working fine
