### ISSUE TITLE
it's not issue - can I ask question ?

### ISSUE THREAD

**Issue by mkhuman34** [binance-exchange/node-binance-api#126]
Dear Jon Eyrick ,

I know it's not for this place but maybe you can help and show to me true way with your great experience .

Im making my own coin exchange project . I did many tools with your help connection with binance , thank you so much. 

Now i need last thing, I need to just 1 my local currency  , there will all is my own structure . 

I need to use there data base and i need to pump data as a candles (1m, 5m, 15m, 30m, 1h, 4h, 1day, 1w ) ...

It's will every new data - i will pump data on websocket. 

But every secong 8 different queries on MySQL - i think it's too much for resources . 

How can I do that ? What can I use ? 

I'm planing for this node.js and MySQL database .

Im doing true or false ? is node.js  ok? is MySQL will work for this ? 

Please show me way with your experience ? Do you have any source files ? Sample projects on github or something ? 

Really I don't know how will I do that ? 

Just i need 1 currency for example BITCOIN / EURO .

I will save bids/asks then i will get data from there, order depth, trade history , candles etc. etc. I don't know how i will do that.

Thank you so much for your help.

Have a nice day !

**Comment by jaggedsoft** [comment]
MySQL is probably too slow
I personally would use Redis .. Sorry I cannot be more helpful
