### ISSUE TITLE
why the binance.buy function can not work?

### ISSUE THREAD

**Issue by jackiewillen** [binance-exchange/node-binance-api#141]
```
    binance.buy("DGDBTC", 0.2, 0.017, { type: 'LIMIT' }, (error, response) => {
        console.log(response);
        console.log(error);
    });

```
When i write these codes, the callback console {} and null.It means the response = {},error =null.Why? It should tell me why the response value is {}, not tell me the error is null.

**Comment by jaggedsoft** [comment]
Maybe you have `test` set to true

**Comment by jackiewillen** [comment]
I just figure this out!! Thank you very much

**Comment by jaggedsoft** [comment]
No problem. Any other questions feel free to ask. Cheers!
