### ISSUE TITLE
Duplicate deletion

### ISSUE THREAD

**Issue by davewang** [binance-exchange/node-binance-api#148]
Because of network slow. `delete context.messageQueue;`  invoke twice 。
https://github.com/binance-exchange/node-binance-api/blob/2caa181daec8b7f01d3ac315edf9940fd98ca618/node-binance-api.js#L1673

https://github.com/binance-exchange/node-binance-api/blob/2caa181daec8b7f01d3ac315edf9940fd98ca618/node-binance-api.js#L1683

**Comment by jaggedsoft** [comment]
Thank you. This has been merged. Great work!!

**Comment by jaggedsoft** [comment]
Available in `v0.7.2`
