### ISSUE TITLE
Name is empty error in withdraw API call

### ISSUE THREAD

**Issue by adityamertia** [binance-exchange/node-binance-api#15]
Hello,

I am trying to call withdraw API. All the API key and secret is enabled and i call withdraw api like below:
binance.withdraw('ETH', gdaxAddress, 0.0205, false, function(response) {
        console.log(response);
});

"Name" isn't a mandatory param. I still get following error response:
{ msg: 'Name is empty.', success: false }

What could be the issue. 

Thanks
Aditya

**Comment by jaggedsoft** [comment]
Thanks for the report!
Hopefully this is fixed in version `0.2.12`
Try updating by navigating to your project directory and issuing a `composer update`
Please let me know if it works or if you still have trouble

**Comment by adityamertia** [comment]
The latest version is 0.2.11. I tried reinstalling node-binance-api but it still points to 0.2.11. composer update requires composer.json. Where do i get it from. It should be simple update from npm ?
