### ISSUE TITLE
Not able to get price in binance.allOrders for type = MARKET & side = BUY/SELL

### ISSUE THREAD

**Issue by raman424** [binance-exchange/node-binance-api#153]
When I am trying to get allOrders from the API, I am getting all the orders but not able to get the price when type  = MARKET and side = BUY or SELL.

```
binance.allOrders('ETHUSDT', (error, orders, symbol) => {
    console.log(symbol+ " orders:", orders);
  });
```

Sample Result:
```
  { symbol: 'ETHUSDT',
    orderId:123456789,
    clientOrderId: 'web_someClientID',
    price: '0.00000000', // This is coming as zero where as expecting price value here.
    origQty: '1.00000000',
    executedQty: '1.00000000',
    status: 'FILLED',
    timeInForce: 'GTC',
    type: 'MARKET', // For type LIMIT, price is coming
    side: 'BUY',
    stopPrice: '0.00000000',
    icebergQty: '0.00000000',
    time: 1234567890,
    isWorking: true },

```
Am I missing something or there is some other way to get it? 
Can you please help resolve the issue?

Regards

**Comment by jaggedsoft** [comment]
Hi there, using `newOrderRespType` with market orders will return much more detailed information.

[newOrderRespType example](https://github.com/jaggedsoft/node-binance-api/blob/master/examples/advanced.md#neworderresptype-example-when-placing-orders)



It returns an array of fills, so you can just take the first one, or create a cost average
