### ISSUE TITLE
Starttime for candlesticks not available...

### ISSUE THREAD

**Issue by mcginnik** [binance-exchange/node-binance-api#155]
**candlesticks often have same kline starttime for different times... want to be able to change starttime**
- feature: please add

**Short Description:**

If I am trying to compare different time frames for BTC for example, all the opening values are the same for 6h, 12h, 1d, and 3d which doesn't really make sense... They are all getting the same default kline start time, and I want to be able to figure out how to get the accurate opening values for all times, otherwise I won't be able to calculate momentum changes.  Is this possible?  Basically for all these different times I expect opening values that would make sense for 6h, 12h, 1d, 3d ago...

***** BTC: 6h: open: 6134.73 - close 6131 @ 2018-6-27 18:16:48 *****
***** BTC: 12h: open: 6134.73 - close 6131 @ 2018-6-27 18:16:48 *****
***** BTC: 1d: open: 6134.73 - close 6134.05 @ 2018-6-27 18:16:48 *****
***** BTC: 3d: open: 6134.73 - close 6131 @ 2018-6-27 18:16:48 *****

  
**Platform:**
- macos

**node version:**
- 9.3

**Long descrption**
- Doing xyz results in ypr and failing when fph

**code**
```
binance.websockets.candlesticks(symbols, timeFrame, (candlesticks) => {
}...
```

**result**
```
***** BTC: 6h: open: 6134.73 - close 6131 @ 2018-6-27 18:16:48 *****
***** BTC: 12h: open: 6134.73 - close 6131 @ 2018-6-27 18:16:48 *****
***** BTC: 1d: open: 6134.73 - close 6134.05 @ 2018-6-27 18:16:48 *****
***** BTC: 3d: open: 6134.73 - close 6131 @ 2018-6-27 18:16:48 *****
```

thank you

**Comment by jaggedsoft** [comment]
Thank you for your report. I still have limited time available in the short term, but I will look in to this as soon as I can!
