### ISSUE TITLE
24h Order History

### ISSUE THREAD

**Issue by mehrdadphp** [binance-exchange/node-binance-api#159]
hello 
I have issue with get "all my order history (https://www.binance.com/userCenter/orderHistory.html ) via api kay. 
I don't know how I can set it ... 
I work with nodes 
pls send for me example code or send more Description and help me . 
Thank you

**Comment by jaggedsoft** [comment]
binance.useServerTime(() =>
	binance.trades("BNBBTC", function(error, trades, symbol) {
	  if ( error ) return console.log(error);
	 	console.log(symbol+" trade history", util.inspect(trades));
	 }, {limit: 2})
);

**Comment by mehrdadphp** [comment]
@jaggedsoft 
I don't want to get only history of one pair.i want all of them in one request.
