### ISSUE TITLE
Getting candlesticks for all Tickers on all intervals is unreliable

### ISSUE THREAD

**Issue by bramvbilsen** [binance-exchange/node-binance-api#166]
I am currently trying to get all candlestick data via the Stream API. But I am facing a big issue:  

**The data does not always arrive in time.**  

So I am trying to get the candlestick data for every symbol on Binance (about 400) for about 5 interval (1m, 5m, 15m, 30m, 1h). I sometimes have to wait over 5 minutes for all data to arrive and of course, by that time, the data is outdated already.  
I looked at your implementation and all looks good there, so perhaps it is something with Binance servers. Or perhaps I am not using the correct websocket endpoint. I am really not sure about what the issue is, so perhaps any one could clarify whether it is just me taxing the Binance servers too much or simply using the wrong endpoint.

**Comment by jaggedsoft** [comment]
hmm, only thing that would make sense to me is processing priority. I have not encountered this problem but I am running on very modern server hardware.
I think the websocket code is almost as efficient as it can be, so these would be my suggestions:

1. Try a faster processor if possible
2. Try connecting to each websocket endpoint individually (do not pass an array) this will test individual connections instead of a combinedStream
3. Worst case scenario split your program into several smaller programs, for example one that handles all BTC pairs, one that handles all ETH pairs, etc. I do not know how to perform proper multithreading on node

**Comment by jaggedsoft** [comment]
I would suggest maybe some other calculations are possibly slowing it down. Are we doing other processing such as technical indicators? If so, this processing can probably be debounced somehow

Are we using the `chart` function? If so, the bottleneck on this function would be the speed of your memory.

The optimal way to design this type of program is probably to have a daemon that is connected to all the websockets and updates this data immediately into a database. Then you run another program that makes decisions based on the contents of the database. I am sure there is a better way but I can't think of one just yet

**Comment by jaggedsoft** [comment]
Another suggestion for a trading bot is to do some kind of screener when your program first starts. This is the approach I take: https://github.com/jaggedsoft/node-binance-api/blob/master/examples/subscribe-to-all.js

1. Download prevDay ticker at program start
2. Filter out only markets we are interested in. For example, has more than 90 BTC daily volume, or some bullish price action, or only BTC markets, etc. This cuts down your subscribed connections by half or more
3. ?????
4. PROFIT!

**Comment by bramvbilsen** [comment]
Wow, thanks for the extremely fast response! I had already started writing my own websocket implementation of the Binance API and I encountered the exact same thing. So it is certainly not the library.  
  
I am also fairly certain it is nothing computational as I simply display the prices and price changes on the screen without manipulating the data. I thought that perhaps Binance slowed me down because I went over their quotas, but I can't seem to find any on their website or docs so I am guessing that is not the problem either.  

But your multithreading suggestion seems like a very reasonable thing to try out!  
Again, thanks for the fast response!

**Comment by jaggedsoft** [comment]
Good luck friend
I do believe it is computational, the symptoms are as if it's not able to process all of the data in time so it just snowballs and gets worse (on linux you can type `uptime` to see the load average, or use `top` to see if it's using too much CPU)

If you are doing this on a VPS, I would suggest trying it on your own computer instead
And vice versa, if you're doing this on your computer, try doing it from a VPS. my digitalocean has a 1000mbit connection and works very well for me

Ciao

**Comment by jaggedsoft** [comment]
The most ideal option I can think of would consist of you generating the OHLC data yourself
This data is generated using only the stream of the latest trades and keeping track of the price change over time (open, high, low, close)
i.e, if a minute has passed on a 1m chart, new candle.

It is much more efficient to monitor the trades stream of all symbols, as shown in https://github.com/jaggedsoft/node-binance-api/blob/master/examples/subscribe-to-all.js

**Comment by jaggedsoft** [comment]
Simplest way I can think of to subscribe to all trade streams (just did this as an experiment)
```js
(async () => {
  const axios = require('axios');
  const WebSocket = require('ws');
  let streams = [];
  let markets = [];
  let prevDay = await axios.get('https://api.binance.com/api/v1/ticker/24hr');
  for ( let obj of prevDay.data ) {
    markets.push(obj.symbol);
    streams.push(obj.symbol.toLowerCase()+'@aggTrade');
  }
  console.log(markets);
  
  const ws = new WebSocket('wss://stream.binance.com:9443/stream?streams='+streams.join('/'));
  ws.on('message', function(payload) {
    let json = JSON.parse(payload), stream = json.stream, data = json.data;
    if ( data.e == 'aggTrade' ) {
      console.log(data.s+' price: '+data.p);
    } else console.log(stream, data);
  });
})();
```

**Comment by bramvbilsen** [comment]
I did something very similar but then with the Candlesticks Stream. I tried it using both your wonderful node JS wrapper and my own websockets implementation but the issue persists.
Here is a more exact description of my issue:

> I am pulling candlestick data (via websockets) for all symbols, for 5 different intervals and I keep the price of all symbols for every interval in an Object. If I then (5 minutes later) `console.log` my Object with all the data, I can clearly see that I do not have all data. Several intervals are missing.

I created a separate project just doing that to make sure that there weren't any bottlenecks in the project I am using this for. Same result...   
Could you perhaps run this code and see if you are running into the same issue?
```javascript
const Binance = require("node-binance-api");
const binance = new Binance();

async function getAllTickerSymbols(callback) {
	binance.prices(callback);
}

function startPullingData(symbols, intervals, callback) {
	intervals.forEach(interval => {
		binance.websockets.candlesticks(symbols, interval, callback);
	});
}

async function start() {
	const intervals = ["1m", "5m", "15m", "30m", "1h"];
	const res = {};
	getAllTickerSymbols((error, tickers) => {
		if (error) {
			throw new Error("Aborting, couldn't get all symbols");
		}
		const symbols = Object.keys(tickers);
		symbols.forEach(symbol => {
			res[symbol] = {};
		});
		startPullingData(symbols, intervals, data => {
			res[data.s][data.k.i] = data.k.c;
		});
		setTimeout(() => {
			// Clear the console.
			console.log("\x1Bc");
			console.log(res);
		}, 5 * 60 * 1000);
	});
}

start();

```

**Comment by jaggedsoft** [comment]
What I would do in this situation is to run the `chart` function on 1 minute, but with the limit increased from 500 to 1000.
Then I would convert the 1 minute candlestick data into longer timeframes using math. For example this library https://github.com/Algorithmic-Trading/forex.analytics
has this function `convertOHLC` Converts OHLC data set to a larger timeframe (e.g. from 5 minute interval to 30 minute interval)


I just realized the `chart` function has no way to adjust the limit so it's stuck at the default of 500 results. I will make it possible to increase that to 1000 next release

**Comment by jaggedsoft** [comment]
Available in v0.8.6 https://github.com/jaggedsoft/node-binance-api/commit/3c03495f6231628771f5fda27065843b9e3a48be
Converting 1m charts to 30m will give you a maximum of 32 candles I believe. 5m might be better if you want longer term

```js
binance.websockets.chart( "BTCUSDT", "1m", ( symbol, interval, chart ) => {
    let tick = binance.last( chart );
    const last = chart[tick].close;
    console.log( chart );
    // Optionally convert 'chart' object to array:
    // let ohlc = binance.ohlc(chart);
    // console.log(symbol, ohlc);
    console.log( symbol + " last price: " + last, "length: " + Object.keys( chart ).length );
}, 1000 ); // limit is the last parameter (max 1000)
```

**Comment by bramvbilsen** [comment]
@jaggedsoft That sounds promising, less demanding for the Binance server and less waiting for me!
  
It is a shame that Binance only allows getting the last 1000 candles though, it would make much more sense to have 1440 candles as a limit so you can get all candles of all the intervals for the past 24 hours. The 1 minute interval is kind of left out 😞   
Anyhow, I am sure I can work around that!  

I will try this out this evening and let you know.  
Thank you for the incredibly fast update to allow for 1000 candles!

**Comment by jaggedsoft** [comment]
No worries friend. Unfortunately this method also comes with a caveat .. loading this historical data with 1000 limit uses up a lot of your API quota. So you probably need to delay 350ms between new calls to `chart` .. which would result in a warm up time of around two to three minutes before your program is correctly streaming all candles.. I just thought about this restriction. Nothing is easy! haha. But I guess that is part of the challenge here.

**Comment by bramvbilsen** [comment]
It does BTW not only happen with `LRCETH`, I just got the same issue with `ZRXBTC` for example and have seen it with other trading pairs as well.

**Comment by jaggedsoft** [comment]
I would suggest we extend the error handler to handle empty responses
```js
                            if (error) {
                                reject(error);
                            }
```
And if this happens put it in a queue to retry
Only thing I can think of

**Comment by jaggedsoft** [comment]
I haven't checked out this guys code in awhile https://github.com/binance-exchange/binance-api-node
But he might have a solution I haven't thought of

**Comment by bramvbilsen** [comment]
Alright, I am going to try the fork you just mentioned. It seems to also have types for typescript which is great!
