### ISSUE TITLE
Prev/Total in BTC withdrawal

### ISSUE THREAD

**Issue by izhtrade** [binance-exchange/node-binance-api#171]
Hi

Please tell me how to find out the current limit and the balance in BTС for withdrawal of funds from the user through api.

All i found is
https://www.binance.com/assetWithdraw/getWithdrawNum.html

but this is not correct when using api.

Thank.

**Comment by jaggedsoft** [comment]
https://t.me/binance_api_english

**Comment by izhtrade** [comment]
and what, is it there?
