### ISSUE TITLE
https://t.me/binance_api_english

### ISSUE THREAD

**Issue by izhtrade** [binance-exchange/node-binance-api#172]
https://t.me/binance_api_english

_Originally posted by @jaggedsoft in https://github.com/binance-exchange/node-binance-api/issues/171#issuecomment-449383201_

and what, is it there?

**Comment by jaggedsoft** [comment]
Sorry friend, if you want support from Binance you must go through https://t.me/binance_api_english

I have made several proposals for improving the API and providing better support but they have shot them down.
