### ISSUE TITLE
Limit order not working..!

### ISSUE THREAD

**Issue by Gennttii** [binance-exchange/node-binance-api#174]
Hi, I tried to open limit orders with callback and without like this : 

`binance.sell("TUSDUSDT", 10, 0.95);

    binance.buy("TUSDUSDT", 10, 0.95, {type:'LIMIT'}, (error, response) => {
        console.log("Limit Buy response", response);
        console.log("order id: " + response.orderId);
      });`

But its not working, not opening the order.. Its showing me this: 

```
Limit Buy response {}
order id: undefined
```

I have the initialization like this:

`const binance = require('node-binance-api')().options({
    APIKEY: 'xx',
    APISECRET: 'xx',
    useServerTime: true // If you get timestamp errors, synchronize to server time at startup
});`

**Comment by Gennttii** [comment]
still not working, showing a very long error..

**Comment by jaggedsoft** [comment]
`if ( error ) return console.warn(error.msg);`
try that instead
if that doesn't work, try error.body

**Comment by Gennttii** [comment]
error.msg returns undefined.

error.body returns: 
`{"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}`

What should I do :S !

**Comment by jaggedsoft** [comment]
https://github.com/jaggedsoft/node-binance-api/issues/297#issuecomment-429620862

If you need further support please go through https://t.me/binance_api_english

**Comment by Gennttii** [comment]
Okay I found the problem, the minimum is 10, I was trying with 10, but didn't work it should be more than 10, worked with 11..
