### ISSUE TITLE
Trades - all trades

### ISSUE THREAD

**Issue by FiNar76** [binance-exchange/node-binance-api#18]
I am trying to request "all trades" but I cannot find a way to request all trades beside a "declared pair"

e.g. the following works (including the pair NEO-BTC)

```
binance.trades("NEOBTC", function(json) {
console.log("trade history",json);
});
```

but what about to request all the trade history? I have tried the following with no luck... 
```
binance.trades({}, function(json) {
console.log("trade history",json);
});
```

is it a bug or am I missing something?

**Comment by jaggedsoft** [comment]
Thank you for the suggestion!
This has been requested by several people. I am sure binance will add it at some point
