### ISSUE TITLE
arrow functions `this` scope problem in handleSocketOpen, handleSocketClose

### ISSUE THREAD

**Issue by yepp4you** [binance-exchange/node-binance-api#182]
When using the arrow function, this is not an object bound by the bind function. Thus, the object passed in is Binance, not ws
Therefore, this.endpoint is undefined.
const handleSocketOpen = function ( opened_callback ) {
...
}

*) handleSocketClose should also be modified. 
https://github.com/binance-exchange/node-binance-api/blob/18733260d838d756594be8ed06a8a860a29d68f9/node-binance-api.js#L402

**Comment by jaggedsoft** [comment]
thank you for your report

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind

**Comment by yepp4you** [comment]
Using the normal function instead of the arrow function seems to solve the problem.

const handleSocketOpen = function( opened_callback )  {
...
}

const handleSocketClose = function( reconnect, code, reason ) {
...
}

https://hackernoon.com/javascript-es6-arrow-functions-and-lexical-this-f2a3e2a5e8c4

**Comment by jaggedsoft** [comment]
interesting research, thank you for the insight! I will get rid of the arrow functions

**Comment by jaggedsoft** [comment]
I removed the arrow functions in the live branch. I'll push a new update soon, maybe today or tomorrow.
Please subscribe to this repo as it's updated more often: https://github.com/jaggedsoft/node-binance-api/

https://github.com/jaggedsoft/node-binance-api/commit/0647e3ec868d799d4c7cd063de93f2a029f929ef

**Comment by jaggedsoft** [comment]
https://stackoverflow.com/a/2130411/1564919

TIL: Arrow functions pass the 'this' scope automatically. So if we want to switch back to arrow functions we need to just remove the call to .bind(). I was a bit confused before but now it makes more sense
