### ISSUE TITLE
 Is there a solution to find the price of a crypto compared to the date and time?

### ISSUE THREAD

**Issue by alexandrebouttier** [binance-exchange/node-binance-api#186]
Is there a solution to find the price of a crypto compared to the date and time?

**Comment by jaggedsoft** [comment]
You could do this using kline/candlestick information

**Comment by thanhnguyennguyen** [comment]
you can use library `ccxt` to load price history

**Comment by jaggedsoft** [comment]
maybe coingecko or coinpaprika
