### ISSUE TITLE
No error passed as argument to callback functions

### ISSUE THREAD

**Issue by raine** [binance-exchange/node-binance-api#19]
Errors that may occur making requests are not passed to callback functions.

This is a node anti-pattern and breaks automatic promisification of the functions.

### bad

```js
binance.prices(function(ticker) {
  // ...
})
```

### good

```js
binance.prices(function(err, ticker) {
  // ...
})
```

**Comment by jaggedsoft** [comment]
Yes, I understand this and hope to move towards this in future releases. However, these are all breaking changes

**Comment by jaggedsoft** [comment]
This project did a bit better planning in that regard:
https://github.com/binance-exchange/binance-api-node

**Comment by raine** [comment]
> However, these are all breaking changes

Not a problem if you adhere to [semantic versioning](https://semver.org/) which is the standard in nodejs land.

You can release `1.0.0` (currently at `0.3.0`) that is backwards incompatible and no one's code breaks.
