### ISSUE TITLE
WebSocket - subscribing to tickers - connection closed, status code 1011

### ISSUE THREAD

**Issue by SteelBRS** [binance-exchange/node-binance-api#198]
This has begun to happen frequently ... is it a change in policy?
Do I need to register my IP address in my Binance account?
https://binance-docs.github.io/apidocs/futures/en/#10xx-general-server-or-network-issues

**Comment by jaggedsoft** [comment]
Haven't heard anyone reporting issues so I couldn't tell you, but I would assume that it's one of the following:

listenKey must be provided for user data requests (feature request)
futures socket keepalives should be handled automatically (feature request)
Some routes may be required to have IP whitelisting enabled with your IP (?)

**Comment by SteelBRS** [comment]
I think this is one of most idiotic software changes I've encountered in my 20+ year career.
Subscribing to tickers via. a WebSocket ... clearly a public function ... suddenly requires IP whitelisting ... is this how you're defending against DDOS attacks or something? Because it's the wrong way to do it.

**Comment by jaggedsoft** [comment]
couldn't tell you, the problem is likely on binance's side, and I'm not affiliated with Binance. You might have better luck trying the futuresSubscribeSingle endpoint

So far all the endpoints I've been testing seem to be working, I haven't tried the user data endpoints

**Comment by SteelBRS** [comment]
Oh ... sorry ... I thought this was Binance's official github account

**Comment by SteelBRS** [comment]
Well I give up for today
https://www.linkedin.com/posts/steelbrs_cryptocurrency-neversendabankertodoaprogrammersjob-activity-6668474379665514496-8of7
Hopefully they'll unfuckup by tomorrow :smirk:
