### ISSUE TITLE
Monitor depth update "U" and "u" flags sequence

### ISSUE THREAD

**Issue by mfarshada** [binance-exchange/node-binance-api#21]
Here is a suggestion to ensure no depth update is missed (due to network interruptions, etc) by checking that each depth.U flag equals the previous depth.u+1.

```javascript
depthCache: function depthCacheFunction(symbols, callback, limit = 500) {
	for ( let symbol of symbols ) {
		if ( typeof info[symbol] == "undefined" ) info[symbol] = {};
		info[symbol].u = 0;
		depthCache[symbol] = {bids: {}, asks: {}};
		messageQueue[symbol] = [];
		let reconnect = function() {
			if ( options.reconnect ) depthCacheFunction(symbols, callback);
		};
		subscribe(symbol.toLowerCase()+"@depth", function(depth) {
			if ( !info[symbol].u ) {
				messageQueue[symbol].push(depth);
				return;
			}
			if (depth.U <= (info[symbol].u+1)){	//it should normally be ==, but may be < for the first update when depth.U == json.lastUpdateId 
				depthHandler(depth);
				info[symbol].u = depth.u;
				if ( callback ) callback(symbol, depthCache[symbol]);
			} else {
				throw "ERROR: Skipped depth update!";
			} 
		}, reconnect);
		publicRequest(base+"v1/depth", {symbol:symbol, limit:limit}, function(json) {
			info[symbol].u = json.lastUpdateId;
			depthCache[symbol] = depthData(json);
			for ( let depth of messageQueue[symbol] ) 
				if ( depth.u > json.lastUpdateId ) {
					if (depth.U <= (info[symbol].u+1)){	//it should normally be ==, but may be < for the first update when depth.U == json.lastUpdateId 
						depthHandler(depth);
						info[symbol].u = depth.u;
					} else {
						throw "ERROR: Skipped depth update in messageQueue!";
					} 
				}
			delete messageQueue[symbol];
			if ( callback ) callback(symbol, depthCache[symbol]);
		});
	}
},
```
Also removed the unnecessary check for `firstUpdateId` every time `depthHandler()` is called, the task is handled in `depthCache()` where it is done only for initialization.

```javascript
const depthHandler = function(depth) { // Used for websocket @depth
	let symbol = depth.s, obj;
	for ( obj of depth.b ) { //bids
		depthCache[symbol].bids[obj[0]] = parseFloat(obj[1]);
		if ( obj[1] == '0.00000000' ) {
			delete depthCache[symbol].bids[obj[0]];
		}
	}
	for ( obj of depth.a ) { //asks
		depthCache[symbol].asks[obj[0]] = parseFloat(obj[1]);
		if ( obj[1] == '0.00000000' ) {
			delete depthCache[symbol].asks[obj[0]];
		}
	}
};

```
Please let me know what you think of these changes, and thank you for making this great API library available!

**Comment by jaggedsoft** [comment]
Thank you very much! I love the changes. Is this tested enough to be considered stable?

**Comment by mfarshada** [comment]
Yes, this is tested and I have had no issues mot of the times. However, I have got occasional "Skipped depth update" errors, seemingly soon after the depthCache is called for the first time. The errors are infrequent and hard to reproduce, so I am currently not sure if they were true update skips, or the result of a conflict between /depth endpoint and websocket @depth. The most likely cause is that websocket is established with some delay after the cache is initialized by the /depth endpoint, so the updates in between are lost. The fix would be to ensure websocket gets at least the first update before initializing the /depth endpoint. 

Sure, the errors can be handled in any desired way, I just put the 'throw' statements for demo. In principle, if an update is skipped the local cache needs to be re-initialized using the /depth endpoint or the data becomes potentially messed up and useless.
