### ISSUE TITLE
cancel stream after started streaming

### ISSUE THREAD

**Issue by iBasit** [binance-exchange/node-binance-api#23]
I'm using `binance.websockets.trades` and I would like to cancel the streaming data or stop it completely, because I want to restart with new list in the `nodejs socket.io` application. 

Is there a way to stop the streaming or cancel it?

**Comment by jaggedsoft** [comment]
```js
binance.options({
	'APIKEY': '<your key>',
	'APISECRET': '<your secret>',
	'reconnect': false
});
```

You can terminate each websocket endpoint by the id:
```js
binance.websockets.terminate('ethbtc@kline_1m');
```

Or for websockets.trades it would be
```js
binance.websockets.terminate('ethbtc@aggTrades');
```


You can also list / store a reference to each `ws` object:
```js
// List all endpoints
let endpoints = binance.websockets.subscriptions();
for ( let endpoint in endpoints ) {
	console.log(endpoint);
	//binance.websockets.terminate(endpoint);
}
```

**Comment by iBasit** [comment]
Thank you for adding the examples.

is there a way to add new endpoint to existing websocket, just like there is terminate the endpoint?

`binance.websockets.terminate('ethbtc@aggTrades');`  so is there any `binance.websockets.subscribe('ethbtc@aggTrades');`?

**Comment by jaggedsoft** [comment]
Yes
```js
binance.websockets.subscribe("ethbtc@aggTrade", callback);

// example callback
function handle_trades(trades, symbol) {
	console.log(symbol+" trade history", trades);
});
```

**Comment by jaggedsoft** [comment]
Yes
```js
binance.websockets.subscribe("ethbtc@aggTrade", callback);

// example callback
function handle_trades(trades) {
	let {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
	console.log(symbol+" trade update. price: "+price+", quantity: "+quantity+", maker: "+maker);
});
```

**Comment by iBasit** [comment]
I have tried the example from above as folowing

```

// List all endpoints
let endpoints = binance.websockets.subscriptions();
for ( let endpoint in endpoints ) {
	console.log(endpoint);
	binance.websockets.terminate(endpoint);
}

```

after it disconnects, then it starts reconnecting again!? Do you know why it's doing that?

![image](https://user-images.githubusercontent.com/34341/34756120-860af840-f5c0-11e7-91a3-4dd875075a32.png)

**Comment by jaggedsoft** [comment]
as in the example, first, you must disable automatic reconnection of websockets:
```js
binance.options({
	'APIKEY': '<your key>',
	'APISECRET': '<your secret>',
	'reconnect': false
});
```

**Comment by iBasit** [comment]
Yes, I just noticed that, so deleted my post, but was not fast enough.

Thank you

**Comment by iBasit** [comment]
Sorry, I still have a problem.

The connection is closed as the following screenshot. 


![image](https://user-images.githubusercontent.com/34341/34756237-4f704866-f5c1-11e7-9680-2a49ffe6b662.png)


but the callback is still getting triggered after the connection is closed and data is still getting live streamed. very strange!
