### ISSUE TITLE
Getting account updates for multiple users in 1 websocket/stream

### ISSUE THREAD

**Issue by moazzamk** [binance-exchange/node-binance-api#24]
Hi,

Is it possible to get account updates for multiple users in one socket/stream? I am a bit confused because they will have different API keys. If you can show me some example code, that would be great!

(I am writing a dashboard for a friend and me to manage our portfolios)

**Comment by jaggedsoft** [comment]
I don't think this is possible as it stands, but it would be possible to subscribe to two streams and send the results to one callback function
