### ISSUE TITLE
CORS w/Unsigned Endpoints

### ISSUE THREAD

**Issue by GioLogist** [binance-exchange/node-binance-api#27]
Problem: 
Because of CORS and Binance's server config, a server is currently required for accessing any endpoint. While this makes total sense for signed endpoints, its a bit overkill for unsigned endpoints (allPrices, etc). 

Solution:
I see that you guys are running on nginx. You can allow cross origin requests for specific endpoints:

```
location /api/v1/ticker/allPrices {
        add_header 'Access-Control-Allow-Origin' '*';
}
```

This will allow people to contribute much simpler apps, widgets, etc. without having to spin up a server instance 🤘🏻

**Comment by jaggedsoft** [comment]
This is up to binance. I just make the api

**Comment by GioLogist** [comment]
Hah, this is the [second time](https://github.com/aarongarvey/binance/issues/17) this has happened to me today - I thought surely this was the "official one" this time.

Cheers, and great job with the API ✊🏻

**Comment by jaggedsoft** [comment]
It's really hard to get ahold of them with the influx of new users
Your best bet is probably a tech support request on their website

They closed the ability to post issues to their docs repo
https://github.com/binance-exchange/binance-official-api-docs

You can also use the API telegram, but i dont know how many binance devs are in there

**Comment by jaggedsoft** [comment]
Also thank you for your kind words!

**Comment by GioLogist** [comment]
> It's really hard to get ahold of them with the influx of new users

I hear ya. I'll probably take your advice or just revisit this at another time when things have settled. I don't mind having to spin up a server in the meantime 🤘🏻

> Also thank you for your kind words!

Yes, of course. I'll try and contribute @ some point as I use it. Already had a few thoughts.

Only bug I found
- I'm assuming you know about the "1,2,3,4,5,6" debug info showing. I have a conditional to filter that out locally.

Other things I've done locally (I don't mind making a PR if you'd like)
- `symbol` and `price` prop names in prices() object (to match /api/v1/ticker/allPrices)
- utility for splitting the "symbol" (ie: NEOBTC to NEO, BTC)
