### ISSUE TITLE
how to cancel all open orders

### ISSUE THREAD

**Issue by includeleec** [binance-exchange/node-binance-api#3]
https://www.binance.com/restapipub.html#user-content-market-data-endpoints
in official webside, 'orderId' is not required.
if pass orderId = null,can cancel all open orders??

Name | Type | Mandatory | Description
-- | -- | -- | --
symbol | STRING | YES |  
orderId | LONG | NO |  
origClientOrderId | STRING | NO |  
newClientOrderId | STRING | NO | Used to uniquely identify this cancel. Automatically generated by default.
recvWindow | LONG | NO |  
timestamp | LONG | YES

**Comment by jaggedsoft** [comment]
Good idea, thank you for the suggestion.
You will need to update the api with `npm update` in your project directory, then you can run this code:
```js
// Cancel all open orders for a symbol
binance.cancelOrders("XMRBTC", function(response, symbol) {
	console.log(symbol+" cancel response:", response);
});
```

or

```js
binance.cancelOrders("XMRBTC");
```

or

```js
// Cancel all open orders for a symbol
binance.openOrders("XMRBTC", function(json, symbol) {
	for ( let obj of json ) {
		let quantity = obj.origQty - obj.executedQty;
		console.log("cancel order: "+obj.side+" "+symbol+" "+quantity+" @ "+obj.price+" #"+obj.orderId);
		binance.cancel(symbol, obj.orderId, function(response) {
			//console.log("..response: ", response);
		});
	}
});
```

**Comment by jaggedsoft** [comment]
You can also get a list of everything you have on order like this:

```js
// Get list of open orders
binance.balance(function(balances) {
	//console.log("balances()", balances);
	for ( let symbol in balances ) {
		let obj = balances[symbol];
		let onOrder = parseFloat(obj.onOrder);
		//console.log(symbol+" balance: "+obj.available);
		if ( onOrder > 0 ) {
			console.log(symbol+" on order: "+onOrder);
		}
	}
});
```

Will output something like:
```
BTC on order: 0.24301
XMR on order: 945.03
```
