### ISSUE TITLE
Bug at line 531 in the node-binance.api.js

### ISSUE THREAD

**Issue by markwienands** [binance-exchange/node-binance-api#35]
signedRequest(base+'v3/myTrades', {symbol:symbol, ...options}

is the '...' necessary?

**Comment by janderson215** [comment]
I'm having the same issue. I was thinking that I had an issue transpiling the spread operator and my settings were wrong. I'm banging my head against a wall (figuratively) trying to determine the root cause.

**Comment by jaggedsoft** [comment]
This breaking change has been fixed in the latest release. I will cut a new release right now

**Comment by jaggedsoft** [comment]
Electron doesn't support ES6 natively. I am not sure why. The spread operator has been supported for years now.

**Comment by jaggedsoft** [comment]
You can update now. `v0.3.5` is live
