### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by SagiMedina** [binance-exchange/node-binance-api#36]
It seems that there is some limit of the number of open connections with different users.
Or am I doing something wrong?

**Comment by jaggedsoft** [comment]
If you are trying to open multiple websocket connections at once, please add a 150-250ms delay between each new websocket connection

**Comment by SagiMedina** [comment]
Actually, I'm calling binance.options for multiple users.
For some reason users are getting other users information.

**Comment by jaggedsoft** [comment]
You will have to show me an example. Perhaps this is a use case I hadn't thought of

**Comment by SagiMedina** [comment]
```
function startSession(userId, exchangeKeys) {
    sessions[userId] = binance.options(exchangeKeys);
}

function getBalance(userId) {
    return new Promise((resolve, reject) => {
        sessions[userId].balance((data) => {
           if (data) resolve(data);
           else reject();
        });
    });
}
```

**Comment by jaggedsoft** [comment]
Hmm, I see no reason why that wouldn't work. I'll investigate this, but my time is very limited for the near future

Perhaps you will have success with this library

**Comment by jaggedsoft** [comment]
https://github.com/binance-exchange/binance-api-node
