### ISSUE TITLE
variable scope inside websocket

### ISSUE THREAD

**Issue by iBasit** [binance-exchange/node-binance-api#37]
I have list of array, which I pass inside websocket callback, but that array gets updated outside websocket after sometime. But inside callback, it still has old array and its old values, does not syncs with outer array.

```
    let testing = true;
    global.testing = testing;
    
    // live trading
    binance.websockets.trades([‘ETHBTC’], (liveTrades) => {

        if (testing)
            console.log("testing = false"); // testing is always false, never gets true
        else
            console.log("testing = true");
    });

    testing = true;
```

**Comment by jaggedsoft** [comment]
This is normal, javascript has localized scope

My application uses the `global.testing` approach and it works

**Comment by iBasit** [comment]
You are right, it works fine. Error was at mongoDB object merge with local object. Sorry.
