### ISSUE TITLE
async/await does not work on create order / cancel order

### ISSUE THREAD

**Issue by iBasit** [binance-exchange/node-binance-api#46]
I need to create order inside the ticker, but when I use normal create order with `async/await` it does not work, do you know why its not working? have you tried it?

```
export const cancelSellStopOrder = async (id, coin, callback) => {
    return await binance.cancel(coin.symbol, coin.stopId);  // hold the script until callback is returned!
}
```

**Comment by jaggedsoft** [comment]
For async/await I recommend using this library instead
https://github.com/binance-exchange/binance-api-node

**Comment by jaggedsoft** [comment]
It appears there is a way to make this work with the `request` library as shown here:
https://github.com/request/request-promise/issues/132

Looking more in to this
