### ISSUE TITLE
binance.websockets.userData  execution_update gets double executed

### ISSUE THREAD

**Issue by iBasit** [binance-exchange/node-binance-api#47]
https://github.com/binance-exchange/node-binance-api/blob/master/examples/advanced.md#user-data-account-balance-updates-trade-updates-new-orders-filled-orders-cancelled-orders-via-websocket

code sample
```
binance.websockets.userData(balance_update, execution_update);
```

output sample
```
[SELL]SNTETH CANCELED price 0.00031126 quantity 40.00000000 type: STOP_LOSS_LIMIT status: CANCELED order id: 8233160 client id: opd9RzkTItwJfbGigWkDCn Reason: NONE
[SELL]SNTETH CANCELED price 0.00031126 quantity 40.00000000 type: STOP_LOSS_LIMIT status: CANCELED order id: 8233160 client id: opd9RzkTItwJfbGigWkDCn Reason: NONE
```

For some reason `execution_update` is getting triggered twice by one order, try running it with console.log and place demo order on binance or by API code, `execution_update` will throw double message

**Comment by jaggedsoft** [comment]
Thanks, I'll test it when I can. Everything was working when I wrote that months ago, but much has changed since then
