### ISSUE TITLE
response undefined when error occurs.

### ISSUE THREAD

**Issue by milkywayriver** [binance-exchange/node-binance-api#54]
signedRequest(base+endpoint, opt, function(error, response) {
			if ( typeof response.msg !== 'undefined' && response.msg === 'Filter failure: MIN_NOTIONAL' ) {
				console.error('Order quantity too small. See exchangeInfo() for minimum amounts');
			}
			if ( callback ) callback(error, response);
			else console.log(side+'('+symbol+','+quantity+','+price+') ',response);
		}, 'POST');
	};

**Comment by jaggedsoft** [comment]
Thanks. Looking in to this

**Comment by milkywayriver** [comment]
TypeError: Cannot read property 'msg' of undefined
    /node_modules/node-binance-api/node-binance-api.js:143:25

/node_modules/node-binance-api/node-binance-api.js:143
			if ( typeof response.msg !== 'undefined' && response.msg === 'Filter failure: MIN_NOTIONAL' ) {

**Comment by jaggedsoft** [comment]
Perhaps something like this would work
```js
		signedRequest(base+endpoint, opt, function(error, response) {
			if ( !response ) {
				if ( callback ) callback(error, response);
				else console.error('Order() error:', error);
				return;
			}
			if ( typeof response.msg !== 'undefined' && response.msg === 'Filter failure: MIN_NOTIONAL' ) {
				console.error('Order quantity too small. See exchangeInfo() for minimum amounts');
			}
			if ( callback ) callback(error, response);
			else console.log(side+'('+symbol+','+quantity+','+price+') ',response);
		}, 'POST');
```

**Comment by milkywayriver** [comment]
could be. please fix and i'll test.

**Comment by jaggedsoft** [comment]
live in `v0.4.3`
https://github.com/jaggedsoft/node-binance-api/commit/b5bb19292ecf03026680ae929636c060f2d267e5

**Comment by jaggedsoft** [comment]
For anyone else reviewing this, it might be better to check `if ( error ) ` instead, not sure the best way to handle this.
