### ISSUE TITLE
Cors Issue

### ISSUE THREAD

**Issue by codingkapoor** [binance-exchange/node-binance-api#55]
I am trying to consume binance rest apis in a small react app. Following is the issue that I face:

_Failed to load https://api.binance.com/api/v1/ticker/allPrices: No 'Access-Control-Allow-Origin' header is present on the requested resource._

Please suggest. TIA

**Comment by nebsi04** [comment]
I think it is an issue when running in browser localhost. I used a google chrome plugin (named Allow-Control-Allow-Origin: *) to make it work on dev machine.

**Comment by jaggedsoft** [comment]
Yeah, no exchange lets you connect to their API from the browser or plugins unfortunately.
As nebsi mentioned, requires some sort of hack or workaround

**Comment by jaggedsoft** [comment]
My approach has always been to have a data source on my server, I pull from that, it pulls from binance. Annoying but works.
