### ISSUE TITLE
websocket 400

### ISSUE THREAD

**Issue by nebsi04** [binance-exchange/node-binance-api#57]
I'm trying to open a websocket with the following example from documentation:
`binance.websockets.prevDay('BNBBTC', (error, response) => {
	console.log(response);
});`

However, I am getting a 400 response from the server. I noticed in Chrome dev tools that the request was "https://" and not "wss://". So, I tested it in Chrome Simple Websocket client. I changed the "https://" to "wss://" and it worked there but I don't know how to fix it in the program. 

I think the "https://" protocol is being transformed in the request.js document. Am I doing something wrong?

**Comment by jaggedsoft** [comment]
Websockets currently do not propagate the 'error' event. Fixing

**Comment by jaggedsoft** [comment]
Fixed here thank you for the report

https://github.com/binance-exchange/node-binance-api/commit/c158f3f746bbfc4f65f2295f88bd4af10d7ba6d1

For now error will always be null but at least it matches the documentation

**Comment by jaggedsoft** [comment]
Live in `v0.4.4`

**Comment by nebsi04** [comment]
Thanks for the prompt response. I will try this out in a bit. One question. I'm running my ReactJS app on my browser on local host. Does this interfere with binance API functionality?

**Comment by jaggedsoft** [comment]
Don't think so, as long as you can actually send data to binance. They have CORS enabled
