### ISSUE TITLE
feature req: atomically change order

### ISSUE THREAD

**Issue by gebrits** [binance-exchange/node-binance-api#60]
On some Exchange APIs it's possible to atomically change an order. I.e..: withdraw/cancel an order + set a new one. Usescases: changed limit when it's clear it's not going to be filled, etc. 

Thoughts?

**Comment by gebrits** [comment]
@jaggedsoft hmm. Haven't seen any rate-limits like that. By any chance, have you been in contact with the guys at Binance to see if these rates can get documented somewhere?

**Comment by gebrits** [comment]
Rate-limit info is available on the [GET /api/v1/exchangeInfo](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#exchange-information)-endpoint

**Comment by jaggedsoft** [comment]
Yes in addition to those, there are new undocumented rules:
https://support.binance.com/hc/en-us/articles/115003235691-Binance-API-Trading-Rules

**Comment by jaggedsoft** [comment]
Really just need a system to keep track of relevant order id's, amount, and price

```js
global.orders[orderid] = {
	symbol: 'BNBBTC',
	type: 'LIMIT',
	side: 'BUY',
	quantity: 10,
	price: 0.00119471
};
binance.cancel('BNBBTC', orderid, (error, symbol, orderid) => {
    if ( error ) return console.error("cancel("+symbol+") error: ", error);
    let obj = global.orders[orderid];
    binance.order(obj.side, symbol, obj.quantity, obj.price, {type: obj.type}, (error, response) => {
	    console.log("Order response", response);
	    console.log("order id: " + response.orderId);
    });
    delete global.orders[orderid];
});
```
