### ISSUE TITLE
BTCUSDT price always return 0.00000000

### ISSUE THREAD

**Issue by sssimpsonjoshua** [binance-exchange/node-binance-api#61]
When I make a BTCUSDT trade, the price always returns as 0.00000000.

For example, if I were to make a market buy of 0.00003400, the execution_update ws function would return: 

BTCUSDT SELL MARKET ORDER #xxxxxxx (NEW)
..price: 0.00000000, quantity: 0.00003400

Any help would greatly be appreciated! 

Thanks!

**Comment by jaggedsoft** [comment]
Unfortunately market buy prices always come back as 0.00000000
I have spoke to the CTO at binance back in august to try and get them to fix it, to no avail
I wish i had a solution, i'm in the same boat. Have to pull all order history and take the very last entry.. annoying
