### ISSUE TITLE
get_all_orders returning price as 0 on market orders

### ISSUE THREAD

**Issue by harambe623** [binance-exchange/node-binance-api#65]
{'symbol': 'ICXBTC', 'orderId': ********, 'clientOrderId': '****************', **'price': '0.00000000',** 'origQty': '2.00000000', 'executedQty': '2.00000000', 'status': 'FILLED', 'timeInForce': 'GTC', **'type': 'MARKET'**, 'side': 'BUY', 'stopPrice': '0.00000000', 'icebergQty': '0.00000000', 'time': 1516988037639, 'isWorking': True}

**Comment by harambe623** [comment]
This also happens on the socket.

**Comment by jaggedsoft** [comment]
I have requested binance to fix this many times. Nothing I can do
