### ISSUE TITLE
How to fetch a FULL order status

### ISSUE THREAD

**Issue by adityamertia** [binance-exchange/node-binance-api#77]
Hello,
I have been trying to fetch an orders status to look for the price and qty details from the fills. This as explained in the API docs can be fetch by using newOrderRespType ENUM.
`newOrderRespType | ENUM | NO | Set the response JSON. ACK, RESULT, or FULL; default: RESULT.`

```
binance.orderStatus(_SYMBOL_, orderID, newOrderRespType.FULL, function(err, orderStatus, symbol) {
       if(err)
         logger.info(`ERROR: ${err.message}`);
       else{ 
         logger.info(symbol + " order status:" + JSON.stringify(orderStatus));
       }
    });

```
But i get ReferenceError: newOrderRespType is not defined.
Can someone tell how to fetch FULL orderStatus as explained in the API doc @ https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by jaggedsoft** [comment]
Right now it only supports `symbol, orderid`
I'll add the rest of the flags tonight

**Comment by jaggedsoft** [comment]
Thanks for the report!

**Comment by jaggedsoft** [comment]
The orderStatus function now supports newOrderRespType
```js
orderStatus: function(symbol, orderid, callback, flags = {}) {
    let parameters = Object.assign({symbol:symbol, orderId:orderid}, flags);
    signedRequest(base+'v3/order', parameters, function(error, data) {
        if ( callback ) return callback.call(this, error, data, symbol);
    });
},
```

I'll update when the release is live

**Comment by jaggedsoft** [comment]
```js
binance.orderStatus(_SYMBOL_, orderID, function(err, orderStatus, symbol) {
       if(err)
         logger.info(`ERROR: ${err.message}`);
       else{ 
         logger.info(symbol + " order status:" + JSON.stringify(orderStatus));
       }
}, {newOrderRespType: 'FULL'});
```

**Comment by jaggedsoft** [comment]
Available now in `v0.4.11`

**Comment by adityamertia** [comment]
Above code didn't work even now. I get following error:
`ERROR: "{\"code\":-1104,\"msg\":\"Not all sent parameters were read; read '5' parameter(s) but was sent '6'.\"}"`

**Comment by jaggedsoft** [comment]
newOrderRespType, as its name implies, must unfortunately only be available in new orders

**Comment by adityamertia** [comment]
I didn't quite get it. This exists in orderStatus and order status can only be checked for an order which was already placed. And once the order is completed then only there can be any use of FULL to check the details of the fills.
My requirement is to fetch the details of order fills.

**Comment by adityamertia** [comment]
@jaggedsoft any update on this?

**Comment by jaggedsoft** [comment]
I'm afraid not, it appears the deficiency is on the binance side
But I can suggest they provide what you're after

It's also possible that one of these may provide what you want. But I'm not sure the difference between them yet

#### Recent Trades (historicalTrades, recentTrades, aggTrades functions)

```js
binance.aggTrades("BNBBTC", {limit:500}, (error, response)=>{
	console.log("aggTrades", response);
});
```

```js
binance.recentTrades("BNBBTC", (error, response)=>{
	console.log("recentTrades", response);
});
```

```js
binance.historicalTrades("BNBBTC", (error, response)=>{
	console.log("historicalTrades", response);
});
```
