### ISSUE TITLE
Trade Websocket disconnected?

### ISSUE THREAD

**Issue by elmondogri** [binance-exchange/node-binance-api#80]
Hello, 

First thank you for the nice API, I am using it to run a bot on Binance.

I am still testing it but I noticed that after a long time (+/- 24h) trades websockets are disconnecting, and at a point I am not recieving any information anymore, is this a normal behaviour and how can I avoid it?

Thank you

**Comment by jaggedsoft** [comment]
The fix is coming soon. There is now a way to connect to all the trades endpoints through 1 connection and it is _much_ more reliable

**Comment by elmondogri** [comment]
That is exactly what I am looking for, can you give me more information about this solution?

Btw this is a light fast reply :+1:

**Comment by jaggedsoft** [comment]
The solution is a clever one, thanks to @keith1024
https://github.com/binance-exchange/node-binance-api/issues/66

I will keep you updated as we build it out. Some patience will be needed since we are all very busy :)

**Comment by jaggedsoft** [comment]
Also, the latest version automatically reconnects zombie websockets. So it may suffice as a temporary fix

**Comment by keith1024** [comment]
@elmondogri Also note, as per the official Binance web socket API docs, since you mentioned +/-24 hours -

> A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark

But as @jaggedsoft mentioned above, the current version auto reconnects closed sockets, so that should help cover those 24 hour mark server-side disconnects.

**Comment by elmondogri** [comment]
Yes but unfortunatly it sometimes isn t reconnecting so I remain without any message from the websocket and my bot is just waiting.

I will try to update but the version I have is 0.4.4 and I tough it was already auto reconnect right?

**Comment by jaggedsoft** [comment]
In addition to reconnecting on failure, `v0.4.12` has a keep-alive function that will reconnect if no data is received in 30 seconds. That might help
See https://github.com/binance-exchange/node-binance-api/commit/361942296d19fc4f33bfdf8b99005b54cf2e746a

**Comment by elmondogri** [comment]
Thank you I will try this, it looks to be something that can solve my problem.

Also I wanted to ask, is there any forum/discussion board about automated crypto trading?

I have a working bot that is generating good enough income (still simulating) but I have some trouble not about the API but about algorithm, I can't find a way to detect wich one is a trending coin, so my bot is inversting in all of them, and sometime making small or negative ROI for certains coins, well I doubt it is apropriate to talk about it here but could you recommand me a good place for this?

**Comment by jaggedsoft** [comment]
@elmondogri 
Unfortunately algorithmic trading is outside the scope of this discussion here
Though simple price action strategies seem to work well for most people
https://my-pull-zone-tradingwithrayne.netdna-ssl.com/wp-content/uploads/2017/01/The-ultimate-guide-to-price-action-trading.pdf

Others tend to rely on Technical Analysis (I have done this, but it's not for me)
Personally, I lean towards Statistical Analysis myself.
Thanks again for the report, and I hope you find something that works for you :)
