### ISSUE TITLE
TypeScript definition file

### ISSUE THREAD

**Issue by amitdahan** [binance-exchange/node-binance-api#84]
There's no definition file written for this lib.
I'm writing my code using TypeScript and this could help a lot.

I could help by providing a .d.ts file for people like me which can be included in the npm package.

But the best approach would be to convert the current code to TypeScript (wouldn't be too hard, I could do that as well if I'd get an approval from you guys) and future maintenance to be written in TypeScript as well.

**Comment by jaggedsoft** [comment]
Converting the codebase to typescript, at this time, would be unreasonable. But I am absolutely open to this in the future. Thank you for your help

**Comment by jaggedsoft** [comment]
We will consider moving to typescript in the future. For now if you provide a .d.ts file we can include it. Thanks!
New Features Discussion: https://github.com/jaggedsoft/node-binance-api/issues/125

**Comment by amitdahan** [comment]
I'll work on completing the one I was working on 👍

**Comment by bramvbilsen** [comment]
Any update on this?

**Comment by teneon** [comment]
I am also looking for TypeScript definition file for node-binance-api, anyone?

**Comment by lou-bi** [comment]
I know this issue is closed, but I cant find the definition file. Does it exist ?
