### ISSUE TITLE
Error: not opened at WebSocket.ping

### ISSUE THREAD

**Issue by elmondogri** [binance-exchange/node-binance-api#86]
Hello, since my last issue I have updated to v14 and everything seemed to work great but I can see my bot has restarted 13 times in about 7 hours, because of this error:

![img_3896](https://user-images.githubusercontent.com/20752444/35924573-b1c2700c-0c23-11e8-8fa9-c123a4d3b47a.JPG)

Do you know what this is about? Thank you

**Comment by jaggedsoft** [comment]
Is this the latest version? There was a similar bug fixed last version

+ It would be better if you open all of your websocket connections at once now, then you can take advantage of Combined websockets which are more reliable

**Comment by keith1024** [comment]
I see what's going on here. Binance or some other force closes the socket, right as the heartbeat fires, and before any handler has had a chance to attempt to reconnect the socket. Combine streams will definitely curb the chance of this drastically, but it's still possible with them even. I'll look into this fix.

**Comment by jaggedsoft** [comment]
ws `ping()` function will throw an error if it pings while in the 'connecting' state
If we update package.json to require ws @ `^4.0.0`
Then we can take advantage of an error handler with the ping function https://github.com/websockets/ws/commit/30c9f715247b2f5ad0c691e535708f894d82ed2b

But I am not sure what breaking changes WS has introduced since version `3.2.0`

**Comment by keith1024** [comment]
I see. It doesn't seem like there is anything in the breaking changes for [ws@4.0.0](https://github.com/websockets/ws/releases/tag/4.0.0) that would affect us.

Another possible option, is just that we only place the socket into the `subscriptions` object when the `ws.'open'` event is fired?

**Comment by elmondogri** [comment]
Thank you I will update to the new version, is there something to change in my code in order to benefit the combined stream?

Also, still using v14 I had no error anymore since the last 13 hours without making any change.

**Comment by jaggedsoft** [comment]
Yeah the combined stream is a huge innovation (Thank you again keith1024!)
That is the main upgrade in v15, no more timers are needed, just connect to all of them at once instantly

As for the other changes these will be coming soon:
1. upgrade `ws` to latest version
2. Automatic error handling for `ping`
3. Maybe add toggle to disable heartbeat - might be unnecessary

**Comment by elmondogri** [comment]
I can't wait to see those new innovation, thanks to all the contributors for the time you dedicate to this project, it's way more intuitive that the offical api.

But I'd like to know before updating my project to the last 0.4.15, is there any change I should to my code or is the trade function the same for the end user like me?

**Comment by jaggedsoft** [comment]
It's the same. But it won't cause problems now if you pass it an array containing hundreds of symbols, or even every symbol there is

**Comment by jaggedsoft** [comment]
#### Connect to every trades() socket at once
> This is kind of spammy, since it will post the same symbol several times if more than one order was filled. But, it allows you to maintain a ticker that is updated in real time

```js
binance.prevDay(false, (error, prevDay) => {
	// Get a list of all markets/symbols so we can connect to them
	let markets = [];
	for ( let obj of prevDay ) {
		let symbol = obj.symbol;
		console.log(symbol+" volume:"+obj.volume+" change: "+obj.priceChangePercent+"%");
		markets.push(symbol);
	}
	// Connect to every trades socket at once
	binance.websockets.trades(markets, (trades) => {
		let {e:eventType, E:eventTime, s:symbol, p:price, q:quantity, m:maker, a:tradeId} = trades;
		console.log(symbol+": "+price);
	});
});
```

#### Connect to every candlestick endpoint at once to get the last price
```js
binance.prevDay(false, (error, prevDay) => {
	// Get a list of all markets/symbols so we can connect to them
	let markets = [];
	for ( let obj of prevDay ) {
		let symbol = obj.symbol;
		console.log(symbol+" volume:"+obj.volume+" change: "+obj.priceChangePercent+"%");
		markets.push(symbol);
	}
	// Connect to every socket at once to get the last price
	binance.websockets.candlesticks(markets, '1m', (candlestickData) => {
		let tick = binance.last(candlestickData);
		const symbol = candlestickData.s;
		const close = candlestickData[tick].c;
		console.log(symbol+": "+close);
	});
});
```

**Comment by elmondogri** [comment]
Hello, so this morning before going to work I have tried implementing v0.4.15 but it looks like my code isn t working anymore, I have this error:  

> 0|app      | [ Error: closed before the connection is established
> 0|app      |     at WebSocket.terminate (C:\node\bibot6\node_modules\node-binanc
> e-api\node_modules\ws\lib\WebSocket.js:385:28)
> 0|app      |     at Timeout.socketHeartbeat [as _onTimeout] (C:\node\bibot6\node
> _modules\node-binance-api\node-binance-api.js:258:20)
> 0|app      |     at ontimeout (timers.js:475:11)
> 0|app      |     at tryOnTimeout (timers.js:310:5)
> 0|app      |     at Timer.listOnTimeout (timers.js:270:5) ]
> 0|app      | [ 'WebSocket Error: 1247679273', undefined ]
> 0|app      | [ 'WebSocket reconnecting: 1247679273' ]
> 0|app      | [ Error: closed before the connection is established
> 0|app      |     at WebSocket.terminate (C:\node\bibot6\node_modules\node-binanc
> e-api\node_modules\ws\lib\WebSocket.js:385:28)
> 0|app      |     at Timeout.socketHeartbeat [as _onTimeout] (C:\node\bibot6\node
> _modules\node-binance-api\node-binance-api.js:258:20)
> 0|app      |     at ontimeout (timers.js:475:11)
> 0|app      |     at tryOnTimeout (timers.js:310:5)
> 0|app      |     at Timer.listOnTimeout (timers.js:270:5) ]
> 0|app      | [ 'WebSocket Error: undefined', undefined ]
> 0|app      | [ 'WebSocket reconnecting: undefined' ]
> 0|app      | [ 'WebSocket Unexpected response: undefined' ]
> 0|app      | [ '..WebSocket reconnecting: undefined' ]
> 0|app      | [ 'WebSocket Unexpected response: 1247679273' ]
> 0|app      | [ '..WebSocket reconnecting: 1247679273' ]
> 0|app      | [ 'WebSocket Unexpected response: undefined' ]
> 0|app      | [ '..WebSocket reconnecting: undefined' ]
> 0|app      | [ 'WebSocket Unexpected response: 1247679273' ]
> 0|app      | [ '..WebSocket reconnecting: 1247679273' ]
> 0|app      | [ 'WebSocket Unexpected response: undefined' ]
> 0|app      | [ '..WebSocket reconnecting: undefined' ]

![image](https://user-images.githubusercontent.com/20752444/35959937-5c97c7a2-0cb0-11e8-85eb-d3707b03e697.png)

**Comment by jaggedsoft** [comment]
I believe we are all experiencing this problem right now. Binance is showing the markets are still down
https://support.binance.com/hc/en-us/articles/360000713851-System-Upgrade-Extension

You can view exchangeInfo()
https://api.binance.com/api/v1/exchangeInfo
![35951372-0449daac-0c30-11e8-881e-0f1686cfb5f6](https://user-images.githubusercontent.com/4283360/35960059-0d25bff6-0c5d-11e8-942f-8363d966f998.png)

**Comment by elmondogri** [comment]
I understand thank you
