### ISSUE TITLE
Callback for when Binance goes down

### ISSUE THREAD

**Issue by nickreese** [binance-exchange/node-binance-api#87]
So for the past 2 hours I've been getting a ton of websocket errors. (code 1006) After a bunch of digging I finally got on the binance telegram channel and found out it was actually Binance's apis that are down, not something else.

It'd be great if we could build a way to know that binance is down by spotting repeated websocket reconnect fails and repeated api calls with out a success response and then call an options.binanceDown() or something. 

The big issue is that currently it is ONLY the API that is down, not the platform. (I tested executing a small trade)

This should be a major concern for anyone who is hoping to execute more than a few trades an hour and let their bot run over night. 

My plan is to hook my bot up to twillio and fire off a slew of text messages and even calls so I can go cancel open orders manually if it goes down in the middle of the night.

I'm happy to hack something together, but would love other input if anyone has ideas.

**Comment by nickreese** [comment]
So turns out the order that I placed that showed matched isn't showing in my orders. Maybe the froze the state or something.

**Comment by jaggedsoft** [comment]
I suppose we could test the duration since the last trade for specific markets, that would tell you if there have been no trades in a certain time period, for example 5+ minutes

**Comment by jaggedsoft** [comment]
I have found the solution
You can call exchangeInfo()
If the status is "BREAK" then markets are frozen

https://api.binance.com/api/v1/exchangeInfo

**Comment by jaggedsoft** [comment]
There is now a way to check system status
https://api.binance.com/wapi/v3/systemStatus.html
