### ISSUE TITLE
[Question] Why there are two node api repos forked into binance org

### ISSUE THREAD

**Issue by shogunsea** [binance-exchange/node-binance-api#91]
out of curiosity, why there are two repos for node? which one should we use? thanks.

https://github.com/binance-exchange/binance-api-node
https://github.com/binance-exchange/node-binance-api

**Comment by jaggedsoft** [comment]
Either is fine
The development repo: https://github.com/jaggedsoft/node-binance-api
Changes are made here first

Once they are tested and working they get pushed to the stable repo
https://github.com/binance-exchange/node-binance-api

**Comment by jaggedsoft** [comment]
node-binance-api is the one I developed.

Binance-api-node is another one that came later. It has some nicer features, such as promises.
But our library supports combined streams, complete depth cache, and complete chart cache, so it is a little more powerful out of the box

**Comment by adavidof** [comment]
@jaggedsoft This info probably should be in readme, it will be better to understand the difference.
Could you please add these differences to readme?

**Comment by jaggedsoft** [comment]
@adavidof Yes thank you for the suggestion I will do that. I'm trying to get Binance to sponsor continued development in some capacity. There are many improvements I would like to make, especially to order management and documentation, that would have a big impact.

**Comment by adavidof** [comment]
@jaggedsoft 
amazing!
thank you!
