### ISSUE TITLE
-2015 error

### ISSUE THREAD

**Issue by gen4sp** [binance-exchange/node-binance-api#98]
`{"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}`
but api config looks nice.
What could it be?

![binance](https://user-images.githubusercontent.com/4303628/36249437-c2ed12aa-124b-11e8-8a8f-942a78075b2f.png)

**Comment by gen4sp** [comment]
ok, sorry. it was my fault: i mixed up secret key and api key.

**Comment by jaggedsoft** [comment]
Glad you got it sorted. I was going to suggest deleting the key and making a new one :)
